'use client';
import { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, MapPin, ShieldCheck, UploadCloud, CreditCard } from 'lucide-react';
import Link from 'next/link';

type Slot={time:string;available:boolean;startsAt:string};
type Availability={id:string;date:string;slots:Slot[]};
type PaymentMethod={id:string;name:string;type:string;account_label?:string;account_value?:string;instructions?:string;requires_proof?:boolean;active:boolean};
type State={doctor:{name:string;specialty:string;location:string;initials:string};doctorStatus:string;delayMinutes:number;availability:Availability[];consultationPrice:number;currency:string;paymentInstructions:string};

export default function BookingClient(){
 const [data,setData]=useState<State|null>(null); const [methods,setMethods]=useState<PaymentMethod[]>([]); const [date,setDate]=useState(''); const [startsAt,setStartsAt]=useState(''); const [sent,setSent]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [proof,setProof]=useState<{name:string;dataUrl:string}|null>(null);
 const [form,setForm]=useState({patient:'María González',nationalId:'V-12.345.678',phone:'0412-0000000',email:'',reason:'Consulta de control',paymentMethod:'Pago móvil',paymentReference:'',policyAccepted:false});
 useEffect(()=>{fetch('/api/demo').then(r=>r.json()).then((d:State)=>{setData(d);const first=d.availability[0];setDate(first?.date||'');setStartsAt(first?.slots.find(s=>s.available)?.startsAt||'')});fetch('/api/payment-methods?scope=DOCTOR&slug=sofia-mendoza&active=1').then(r=>r.json()).then(j=>{const ms=j.methods||[];setMethods(ms);if(ms[0])setForm(f=>({...f,paymentMethod:ms[0].name}))})},[]);
 const current=useMemo(()=>data?.availability.find(a=>a.date===date),[data,date]);
 function fileChange(file?:File){if(!file)return;if(file.size>2_000_000){setError('Para el demo usa un comprobante menor de 2 MB.');return}const reader=new FileReader();reader.onload=()=>setProof({name:file.name,dataUrl:String(reader.result)});reader.readAsDataURL(file)}
 async function book(){if(!startsAt||!form.patient||!form.phone||!form.email||!form.paymentReference||!proof||!form.policyAccepted){setError('Completa tus datos, correo, referencia, comprobante y acepta la política.');return}setLoading(true);setError('');const r=await fetch('/api/demo',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'book',...form,startsAt,paymentProofName:proof.name,paymentProofDataUrl:proof.dataUrl})});const j=await r.json();setLoading(false);if(!r.ok){setError(j.error||'No se pudo enviar la solicitud');return}setSent(true)}
 if(!data)return <div className="booking"><div className="container booking-wrap"><div className="profile-card">Cargando Turnavia…</div></div></div>;
 const doctor=data.doctor;
 if(sent)return <div className="booking"><div className="container booking-wrap"><div className="booking-header"><Link href="/" className="brand" style={{justifyContent:'center'}}>Turnavia</Link></div><div className="profile-card" style={{textAlign:'center',padding:'44px 28px'}}><div className="iconbox" style={{margin:'0 auto',width:62,height:62,borderRadius:20}}><CheckCircle2 size={30}/></div><h1 style={{fontSize:34,marginBottom:8}}>Pago enviado para revisión</h1><p className="muted">Tu horario quedó preagendado mientras {doctor.name} o recepción verifica el comprobante.</p><div className="notice" style={{margin:'22px auto',maxWidth:540,textAlign:'left'}}><strong>Cita Premium Preagendada.</strong><br/>No faltes a tu cita. Si no puedes asistir, tendrás una sola reprogramación, sujeta a la próxima disponibilidad de la doctora.</div><div className="button-row" style={{justifyContent:'center'}}><Link href={`/registro?role=PATIENT&email=${encodeURIComponent(form.email)}`} className="btn btn-primary">Crear mi cuenta de paciente</Link><Link href="/paciente?demo=1" className="btn btn-secondary">Ver estado de mi cita</Link></div></div></div></div>;
 return <div className="booking"><div className="container booking-wrap"><div className="booking-header"><Link href="/" className="brand" style={{justifyContent:'center'}}>Turnavia</Link><p className="muted">Reserva, paga y confirma tu consulta</p></div><section className="profile-card"><div className="profile-top"><div className="profile-avatar">{doctor.initials}</div><div><h1 style={{fontSize:25,margin:'0 0 4px'}}>{doctor.name}</h1><div className="muted">{doctor.specialty}</div><div className="row muted" style={{fontSize:13,marginTop:8}}><MapPin size={15}/>{doctor.location}</div></div></div>
 <div className="notice" style={{marginTop:18}}><div className="row space"><span><strong>Consulta Premium Preagendada</strong><br/><span className="muted">Pago previo requerido para confirmar el cupo.</span></span><strong style={{fontSize:24}}>{data.currency} {data.consultationPrice}</strong></div></div>
 {data.doctorStatus==='DELAYED'&&<div className="notice" style={{marginTop:12}}>La doctora presenta aproximadamente {data.delayMinutes} minutos de retraso.</div>}
 <hr style={{border:0,borderTop:'1px solid var(--line)',margin:'24px 0'}}/><strong>1. Selecciona el día</strong><div className="date-tabs">{data.availability.map(a=><button key={a.id} className={`date-tab ${date===a.date?'active':''}`} onClick={()=>{setDate(a.date);setStartsAt(a.slots.find(s=>s.available)?.startsAt||'')}}><strong>{new Date(a.date+'T12:00:00').toLocaleDateString('es-VE',{weekday:'short',day:'2-digit'})}</strong><div className="muted" style={{fontSize:11,marginTop:3}}>{new Date(a.date+'T12:00:00').toLocaleDateString('es-VE',{month:'short'})}</div></button>)}</div>
 <div style={{marginTop:22}}><strong>2. Selecciona la hora</strong><div className="booking-slots">{current?.slots.map(s=><button disabled={!s.available} type="button" className={startsAt===s.startsAt?'selected':''} onClick={()=>setStartsAt(s.startsAt)} key={s.startsAt}>{s.time}</button>)}</div></div>
 <div style={{marginTop:26}}><strong>3. Tus datos</strong><div className="form"><div className="field"><label>Nombre completo</label><input value={form.patient} onChange={e=>setForm({...form,patient:e.target.value})}/></div><div className="row" style={{alignItems:'stretch'}}><div className="field" style={{flex:1}}><label>Cédula</label><input value={form.nationalId} onChange={e=>setForm({...form,nationalId:e.target.value})}/></div><div className="field" style={{flex:1}}><label>Teléfono</label><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div></div><div className="field"><label>Correo para confirmaciones</label><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="correo@ejemplo.com"/></div><div className="field"><label>Motivo breve</label><textarea rows={3} value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></div></div></div>
 <div style={{marginTop:26}}><strong>4. Registra el pago</strong><div className="notice" style={{marginTop:10}}>{data.paymentInstructions}</div><div className="form"><div className="field"><label>Método de pago</label><select value={form.paymentMethod} onChange={e=>setForm({...form,paymentMethod:e.target.value})}>{methods.length?methods.map(m=><option key={m.id} value={m.name}>{m.name}</option>):<option>No hay métodos activos</option>}</select></div>{methods.filter(m=>m.name===form.paymentMethod).map(m=><div className="notice" key={m.id}><strong>{m.name}</strong><br/>{m.account_label&&<>{m.account_label}: <strong>{m.account_value}</strong><br/></>}{m.instructions}</div>)}<div className="field"><label>Número / referencia del pago</label><input placeholder="Ej. 458923" value={form.paymentReference} onChange={e=>setForm({...form,paymentReference:e.target.value})}/></div><div className="field"><label>Comprobante</label><label className="btn btn-secondary" style={{width:'fit-content',cursor:'pointer'}}><UploadCloud size={16}/> {proof?proof.name:'Subir capture / comprobante'}<input type="file" accept="image/*,.pdf" style={{display:'none'}} onChange={e=>fileChange(e.target.files?.[0])}/></label></div></div></div>
 <label className="notice row" style={{marginTop:16,alignItems:'flex-start',cursor:'pointer'}}><input type="checkbox" checked={form.policyAccepted} onChange={e=>setForm({...form,policyAccepted:e.target.checked})}/><span><strong>Acepto la política de Cita Premium Preagendada.</strong><br/>Entiendo que la cita se confirma al aprobarse el pago y que, si no asisto, podré reprogramarla una sola vez en una fecha futura disponible de la doctora.</span></label>
 {error&&<div className="notice danger" style={{marginTop:14}}>{error}</div>}<div className="notice row" style={{marginTop:16,alignItems:'flex-start'}}><ShieldCheck size={17} style={{flex:'0 0 auto',marginTop:2}}/><span>La doctora o recepción revisará el comprobante antes de confirmar la cita.</span></div><button disabled={loading||!startsAt} className="btn btn-primary" style={{width:'100%',marginTop:16,padding:15}} onClick={book}><CreditCard size={17}/>{loading?'Enviando…':`Enviar pago y preagendar · ${data.currency} ${data.consultationPrice}`}</button></section></div></div>
}
