'use client';
import { Suspense, useEffect,useState } from 'react';
import { useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { Brand } from '@/components/Brand';
import { CreditCard, Bitcoin, ShieldCheck } from 'lucide-react';

function PagoContent(){
 const sp=useSearchParams(); const id=sp.get('client')||''; const [c,setC]=useState<any>(null); const [ref,setRef]=useState(''); const [busy,setBusy]=useState(''); const [msg,setMsg]=useState('');
 useEffect(()=>{if(id)fetch('/api/clients?id='+encodeURIComponent(id)).then(r=>r.json()).then(j=>setC(j.client))},[id]);
 const clinic=c?.type?.startsWith('Clínica'); const initial=clinic?149:40; const monthly=clinic?49:15; const paypalUser='jorgeluisananguren@gmail.com'; const binanceUid='182547235';
 async function sendManual(method:'PAYPAL'|'BINANCE'){if(!ref)return setMsg('Escribe la referencia o ID de la transacción.');setBusy(method.toLowerCase());const comment=`TURNAVIA - ${c.name}`;const r=await fetch('/api/payments/binance',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({clientId:id,reference:ref,comment,paymentMethod:method})});const j=await r.json();setBusy('');if(j.ok){setMsg('Pago enviado a revisión. Verificaremos la referencia y activaremos la cuenta.');setC(j.client)}else setMsg(j.error)}
 if(!id)return <main className="demo-chooser"><div className="container booking-wrap"><Brand/><div className="profile-card" style={{marginTop:30}}>Falta identificar la cuenta. Vuelve a Activar Turnavia.</div></div></main>;
 return <main className="demo-chooser"><div className="container booking-wrap"><div className="row space"><Brand/><Link href="/" className="btn btn-secondary">Inicio</Link></div><div className="demo-head"><span className="eyebrow"><ShieldCheck size={15}/> Pago seguro</span><h1>Continúa con TURNAVIA</h1><p className="muted">{c?<>Cuenta: <strong>{c.name}</strong></>:'Cargando cuenta...'}</p></div>{c&&<><section className="profile-card"><h2>Tu pago inicial</h2><div className="stat-grid" style={{gridTemplateColumns:'repeat(3,1fr)'}}><div className="stat"><small>Activación</small><div className="n">${clinic?100:25}</div></div><div className="stat"><small>Primer mes</small><div className="n">${monthly}</div></div><div className="stat"><small>Total hoy</small><div className="n">${initial}</div></div></div><p className="muted">Después de este pago, la renovación es de <strong>${monthly}/mes</strong>.</p></section><div style={{height:16}}/><section className="grid-3" style={{gridTemplateColumns:'1fr 1fr'}}><div className="card"><div className="iconbox"><CreditCard/></div><h3>PayPal</h3><p>Realiza el pago manualmente y luego registra aquí la referencia o ID de la operación.</p><div className="notice" style={{marginTop:14}}><strong>Cuenta PayPal TURNAVIA</strong><br/>Correo: <strong>{paypalUser}</strong><br/><br/>Concepto sugerido:<br/><strong>TURNAVIA - {c.name}</strong></div><div className="field" style={{marginTop:12}}><label>Referencia / ID de transacción</label><input value={ref} onChange={e=>setRef(e.target.value)} placeholder="Ej. ID de PayPal"/></div><button className="btn btn-primary" style={{marginTop:12,width:'100%'}} onClick={()=>sendManual('PAYPAL')} disabled={!!busy}>{busy==='paypal'?'Enviando...':'Enviar PayPal a revisión'}</button></div><div className="card"><div className="iconbox"><Bitcoin/></div><h3>Binance</h3><p>Realiza el pago manualmente y luego registra aquí el ID o referencia de la operación.</p><div className="notice" style={{marginTop:14}}><strong>Binance TURNAVIA</strong><br/>UID: <strong>{binanceUid}</strong><br/><br/>Concepto sugerido:<br/><strong>TURNAVIA - {c.name}</strong></div><div className="field" style={{marginTop:12}}><label>Referencia / ID de transacción</label><input value={ref} onChange={e=>setRef(e.target.value)} placeholder="Ej. 873921..."/></div><button className="btn btn-secondary" style={{marginTop:12,width:'100%'}} onClick={()=>sendManual('BINANCE')} disabled={!!busy}>{busy==='binance'?'Enviando...':'Enviar Binance a revisión'}</button></div></section>{msg&&<div className="notice" style={{marginTop:18}}>{msg}</div>}<div className="notice" style={{marginTop:18}}>Estado actual: <strong>{c.status}</strong>. Los pagos por PayPal y Binance se revisan manualmente antes de activar la cuenta.</div></>}</div></main>
}
export default function Pago(){return <Suspense fallback={<main className="demo-chooser"><div className="container booking-wrap"><Brand/><div className="profile-card">Cargando pago...</div></div></main>}><PagoContent/></Suspense>}
