'use client';
import { Suspense, useEffect,useState } from 'react';
import { useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { Brand } from '@/components/Brand';
import { CreditCard, Bitcoin, ShieldCheck } from 'lucide-react';

function PagoContent(){
 const sp=useSearchParams(); const id=sp.get('client')||''; const [c,setC]=useState<any>(null); const [ref,setRef]=useState(''); const [busy,setBusy]=useState(''); const [msg,setMsg]=useState('');
 useEffect(()=>{if(id)fetch('/api/clients?id='+encodeURIComponent(id)).then(r=>r.json()).then(j=>setC(j.client))},[id]);
 const clinic=c?.type?.startsWith('Clínica'); const initial=clinic?149:40; const monthly=clinic?49:15; const binanceUid=process.env.NEXT_PUBLIC_BINANCE_UID||'Configurar UID antes de producción'; const binanceLabel=process.env.NEXT_PUBLIC_BINANCE_PAYMENT_LABEL||'Binance TURNAVIA';
 async function paypal(){setBusy('paypal');setMsg('');const r=await fetch('/api/payments/paypal/create',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({clientId:id})});const j=await r.json();setBusy('');if(j.approveUrl)location.href=j.approveUrl;else setMsg(j.error||'No se pudo iniciar PayPal')}
 async function binance(){if(!ref)return setMsg('Escribe la referencia o ID de transacción de Binance.');setBusy('binance');const comment=`TURNAVIA - ${c.name}`;const r=await fetch('/api/payments/binance',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({clientId:id,reference:ref,comment})});const j=await r.json();setBusy('');if(j.ok){setMsg('Pago enviado a revisión. Nosotros verificamos la referencia y activamos la cuenta.');setC(j.client)}else setMsg(j.error)}
 if(!id)return <main className="demo-chooser"><div className="container booking-wrap"><Brand/><div className="profile-card" style={{marginTop:30}}>Falta identificar la cuenta. Vuelve a Activar Turnavia.</div></div></main>;
 return <main className="demo-chooser"><div className="container booking-wrap"><div className="row space"><Brand/><Link href="/" className="btn btn-secondary">Inicio</Link></div><div className="demo-head"><span className="eyebrow"><ShieldCheck size={15}/> Pago seguro</span><h1>Continúa con TURNAVIA</h1><p className="muted">{c?<>Cuenta: <strong>{c.name}</strong></>:'Cargando cuenta...'}</p></div>{c&&<><section className="profile-card"><h2>Tu pago inicial</h2><div className="stat-grid" style={{gridTemplateColumns:'repeat(3,1fr)'}}><div className="stat"><small>Activación</small><div className="n">${clinic?100:25}</div></div><div className="stat"><small>Primer mes</small><div className="n">${monthly}</div></div><div className="stat"><small>Total hoy</small><div className="n">${initial}</div></div></div><p className="muted">Después de este pago, la renovación es de <strong>${monthly}/mes</strong>.</p></section><div style={{height:16}}/><section className="grid-3" style={{gridTemplateColumns:'1fr 1fr'}}><div className="card"><div className="iconbox"><CreditCard/></div><h3>PayPal</h3><p>Confirmación automática. Al completar el pago, TURNAVIA puede activar tu cuenta sin esperar revisión manual.</p><button className="btn btn-primary" style={{marginTop:18,width:'100%'}} onClick={paypal} disabled={!!busy}>{busy==='paypal'?'Conectando...':`Pagar $${initial} con PayPal`}</button></div><div className="card"><div className="iconbox"><Bitcoin/></div><h3>Binance</h3><p>Realiza el pago al dato indicado y luego registra aquí el ID o referencia de la operación.</p><div className="notice" style={{marginTop:14}}><strong>{binanceLabel}</strong><br/>UID / dato de pago: <strong>{binanceUid}</strong><br/><br/>Si Binance permite comentario/descripción, escribe:<br/><strong>TURNAVIA - {c.name}</strong></div><div className="field" style={{marginTop:12}}><label>Referencia / ID de transacción</label><input value={ref} onChange={e=>setRef(e.target.value)} placeholder="Ej. 873921..."/></div><button className="btn btn-secondary" style={{marginTop:12,width:'100%'}} onClick={binance} disabled={!!busy}>{busy==='binance'?'Enviando...':'Enviar pago a revisión'}</button></div></section>{msg&&<div className="notice" style={{marginTop:18}}>{msg}</div>}<div className="notice" style={{marginTop:18}}>Estado actual: <strong>{c.status}</strong>. Los pagos por PayPal se validan mediante PayPal; los de Binance requieren revisión de referencia antes de activar.</div></>}</div></main>
}
export default function Pago(){return <Suspense fallback={<main className="demo-chooser"><div className="container booking-wrap"><Brand/><div className="profile-card">Cargando pago...</div></div></main>}><PagoContent/></Suspense>}
