'use client';
import { useEffect, useMemo, useState } from 'react';
import { Sidebar } from '@/components/Sidebar';
import { CalendarPlus, Clock3, MapPin, ToggleRight, Link2, Share2, CreditCard, Settings2, Eye } from 'lucide-react';
import { StatusPill } from '@/components/StatusPill';
import { PaymentMethodsManager } from '@/components/PaymentMethodsManager';
const label:any={AWAITING_PAYMENT:'Esperando pago',PAYMENT_REVIEW:'Pago en revisión',PAYMENT_REJECTED:'Pago rechazado',CONFIRMED:'Confirmado',ON_THE_WAY:'En camino',ARRIVED:'Ya llegó',IN_CONSULTATION:'En consulta',COMPLETED:'Atendido',CANCELLED:'Cancelado',NO_SHOW:'No asistió'};
export default function Medico(){
 const [data,setData]=useState<any>(null); const [modal,setModal]=useState<'availability'|'status'|'settings'|null>(null); const [toast,setToast]=useState(''); const [av,setAv]=useState({date:'2026-09-26',start:'08:00',end:'12:00',slotMinutes:30}); const [status,setStatus]=useState({status:'NORMAL',delayMinutes:0}); const [settings,setSettings]=useState({consultationPrice:30,currency:'USD',paymentInstructions:''});
 const load=()=>fetch('/api/demo').then(r=>r.json()).then((d:any)=>{setData(d);setSettings({consultationPrice:d.consultationPrice||30,currency:d.currency||'USD',paymentInstructions:d.paymentInstructions||''})}); useEffect(()=>{load()},[]);
 const today=useMemo(()=>data?.appointments.filter((a:any)=>a.startsAt.startsWith('2026-09-18')&&!['CANCELLED','PAYMENT_REJECTED'].includes(a.status))||[],[data]);
 async function post(body:any){const r=await fetch('/api/demo',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok){setToast(j.error||'No se pudo completar');return}await load();setModal(null);setToast('Cambios guardados');setTimeout(()=>setToast(''),1800)}
 async function copy(){await navigator.clipboard.writeText(location.origin+'/reservar/sofia-mendoza');setToast('Enlace copiado');setTimeout(()=>setToast(''),1800)} async function share(){const url=location.origin+'/reservar/sofia-mendoza';if(navigator.share)await navigator.share({title:'Reserva tu consulta',text:'Reserva tu cita con la Dra. Sofía Mendoza en Turnavia',url});else copy()}
 if(!data)return <div className="dashboard"><Sidebar role="medico"/><main className="main">Cargando…</main></div>;
 const review=data.appointments.filter((a:any)=>a.status==='PAYMENT_REVIEW'); const confirmed=today.filter((a:any)=>['CONFIRMED','ON_THE_WAY','ARRIVED','IN_CONSULTATION','COMPLETED'].includes(a.status)); const income=confirmed.length*(data.consultationPrice||0);
 return <div className="dashboard"><Sidebar role="medico"/><main className="main"><div className="topbar"><div><div className="muted" style={{fontSize:13}}>Agenda y pagos</div><h1>Buenos días, Dra. Sofía</h1></div><span className="pill"><span className="live-dot"/> {data.doctorStatus==='DELAYED'?`Retraso · ${data.delayMinutes} min`:data.doctorStatus==='SUSPENDED'?'Consulta suspendida':'Consultando normalmente'}</span></div>
 <div className="stat-grid"><div className="stat"><small>Citas confirmadas</small><div className="n">{confirmed.length}</div></div><div className="stat"><small>Pagos por revisar</small><div className="n">{review.length}</div></div><div className="stat"><small>Precio consulta</small><div className="n">{data.currency} {data.consultationPrice}</div></div><div className="stat"><small>Ingresos programados</small><div className="n">{data.currency} {income}</div></div></div>
 <section className="panel" style={{marginBottom:18}}><div className="row space"><div><h2>Pagos de citas</h2><div className="muted" style={{fontSize:13}}>La cita solo se confirma cuando apruebas el comprobante.</div></div><button className="btn btn-secondary" onClick={()=>setModal('settings')}><Settings2 size={16}/> Precio y pagos</button></div><table className="table"><thead><tr><th>Paciente</th><th>Fecha</th><th>Monto</th><th>Método / referencia</th><th>Comprobante</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{data.appointments.filter((a:any)=>a.paymentReference).map((a:any)=><tr key={a.id}><td><strong>{a.patient}</strong></td><td>{new Date(a.startsAt).toLocaleString('es-VE',{dateStyle:'short',timeStyle:'short'})}</td><td>{a.currency} {a.consultationPrice}</td><td>{a.paymentMethod}<div className="muted" style={{fontSize:12}}>{a.paymentReference}</div></td><td>{a.paymentProofDataUrl?<a className="btn btn-secondary" style={{padding:'7px 10px'}} target="_blank" href={a.paymentProofDataUrl}><Eye size={14}/> Ver</a>:<span className="muted">{a.paymentProofName||'—'}</span>}</td><td><StatusPill tone={a.status==='PAYMENT_REVIEW'?'warn':a.status==='PAYMENT_REJECTED'?'bad':'ok'}>{label[a.status]||a.status}</StatusPill></td><td>{a.status==='PAYMENT_REVIEW'?<div className="status-actions"><button onClick={()=>post({action:'approve_payment',id:a.id})}>Aprobar pago</button><button className="danger" onClick={()=>post({action:'reject_payment',id:a.id})}>Rechazar</button></div>:<span className="muted">—</span>}</td></tr>)}</tbody></table></section>
 <PaymentMethodsManager scope="DOCTOR" slug="sofia-mendoza"/><div className="panel-grid"><section className="panel"><div className="row space"><h2>Agenda</h2><button className="btn btn-secondary" onClick={()=>setModal('availability')}><CalendarPlus size={16}/> Nueva disponibilidad</button></div>{today.map((a:any)=><div className="appointment" key={a.id}><div className="time">{new Date(a.startsAt).toLocaleTimeString('es-VE',{hour:'2-digit',minute:'2-digit'})}</div><div><strong>{a.patient}</strong><div className="muted" style={{fontSize:12,marginTop:3}}>{a.status==='PAYMENT_REVIEW'?'Esperando validación de pago':'Consulta presencial'}</div></div><StatusPill tone={a.status==='PAYMENT_REVIEW'?'warn':['ARRIVED','IN_CONSULTATION','COMPLETED'].includes(a.status)?'ok':''}>{label[a.status]||a.status}</StatusPill></div>)}</section><aside style={{display:'grid',gap:18}}><section className="panel"><h2>Mi consulta</h2><div className="row" style={{marginBottom:14}}><div className="avatar">{data.doctor.initials}</div><div><strong>{data.doctor.name}</strong><div className="muted" style={{fontSize:12}}>{data.doctor.specialty}</div></div></div><div className="row muted" style={{fontSize:13}}><MapPin size={15}/>{data.doctor.location}</div></section><section className="panel"><h2>Acciones rápidas</h2><div className="quick-grid"><button className="quick" onClick={()=>setModal('availability')}><Clock3 size={18}/><strong>Disponibilidad</strong><small>Publicar horarios</small></button><button className="quick" onClick={()=>setModal('status')}><ToggleRight size={18}/><strong>Estado</strong><small>Normal / retrasado</small></button><button className="quick" onClick={copy}><Link2 size={18}/><strong>Mi enlace</strong><small>Copiar reserva</small></button><button className="quick" onClick={share}><Share2 size={18}/><strong>Compartir</strong><small>Enviar a pacientes</small></button></div></section></aside></div></main>
 {modal==='availability'&&<div className="modal-backdrop"><div className="modal"><h2>Publicar disponibilidad</h2><div className="form"><div className="field"><label>Fecha</label><input type="date" value={av.date} onChange={e=>setAv({...av,date:e.target.value})}/></div><div className="row"><div className="field" style={{flex:1}}><label>Desde</label><input type="time" value={av.start} onChange={e=>setAv({...av,start:e.target.value})}/></div><div className="field" style={{flex:1}}><label>Hasta</label><input type="time" value={av.end} onChange={e=>setAv({...av,end:e.target.value})}/></div></div><div className="field"><label>Duración por paciente</label><select value={av.slotMinutes} onChange={e=>setAv({...av,slotMinutes:Number(e.target.value)})}><option value={20}>20 min</option><option value={30}>30 min</option><option value={45}>45 min</option><option value={60}>60 min</option></select></div></div><div className="button-row" style={{marginTop:18}}><button className="btn btn-primary" onClick={()=>post({action:'add_availability',...av})}>Publicar</button><button className="btn btn-secondary" onClick={()=>setModal(null)}>Cancelar</button></div></div></div>}
 {modal==='status'&&<div className="modal-backdrop"><div className="modal"><h2>Estado de consulta</h2><div className="status-actions"><button className={status.status==='NORMAL'?'active':''} onClick={()=>setStatus({status:'NORMAL',delayMinutes:0})}>🟢 Normal</button><button className={status.status==='DELAYED'?'active':''} onClick={()=>setStatus({...status,status:'DELAYED'})}>🟡 Retrasado</button><button className={status.status==='SUSPENDED'?'active':''} onClick={()=>setStatus({status:'SUSPENDED',delayMinutes:0})}>🔴 Suspendida</button></div>{status.status==='DELAYED'&&<div className="field" style={{marginTop:16}}><label>Minutos aproximados</label><input type="number" value={status.delayMinutes} onChange={e=>setStatus({...status,delayMinutes:Number(e.target.value)})}/></div>}<div className="button-row" style={{marginTop:18}}><button className="btn btn-primary" onClick={()=>post({action:'doctor_status',...status})}>Guardar estado</button><button className="btn btn-secondary" onClick={()=>setModal(null)}>Cancelar</button></div></div></div>}
 {modal==='settings'&&<div className="modal-backdrop"><div className="modal"><h2>Precio y pagos de consulta</h2><div className="form"><div className="row"><div className="field" style={{flex:1}}><label>Precio</label><input type="number" value={settings.consultationPrice} onChange={e=>setSettings({...settings,consultationPrice:Number(e.target.value)})}/></div><div className="field" style={{flex:1}}><label>Moneda</label><select value={settings.currency} onChange={e=>setSettings({...settings,currency:e.target.value})}><option>USD</option><option>EUR</option><option>VES</option></select></div></div><div className="field"><label>Instrucciones visibles al paciente</label><textarea rows={5} value={settings.paymentInstructions} onChange={e=>setSettings({...settings,paymentInstructions:e.target.value})}/></div></div><div className="button-row" style={{marginTop:18}}><button className="btn btn-primary" onClick={()=>post({action:'doctor_settings',...settings})}><CreditCard size={16}/> Guardar</button><button className="btn btn-secondary" onClick={()=>setModal(null)}>Cancelar</button></div></div></div>}
 {toast&&<div className="toast">{toast}</div>}</div>
}
